[package]
name = "niaoge_standard_search"
version = "0.1.0"
description = "国家标准本地检索工具"
authors = ["niaoge123"]
edition = "2021"

[lib]
name = "niaoge_standard_search_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
